#cloud-config
yum_repos:
    docker-ce:
      name: Docker CE
      baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
      enabled: true
      gpgcheck: false
      gpgkey: https://download.docker.com/linux/fedora/gpg

package_update: true
#package_upgrade: true
packages:
  - dnf-plugins-core
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, docker ]
  - [ systemctl, start, docker ]

groups:
  - admingroup: [root,sys]
  - cloud-users
  - docker

users:
  - default
  - name: admin
    groups:
      - sudo
      - docker
      - cloud-users
    sudo:
      - ALL=(ALL:ALL) ALL
    ssh-authorized-keys:
     - ${auth_public_key}
    lock_passwd: true

ssh_deletekeys: false

final_message: "The system is finally up, after $UPTIME seconds"

write_files:
  - path: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375
