version: '3'

services:
  postgres:
    container_name: schedule-db
    image: postgres
    env_file: .env
    networks:
      - schedule_network
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  redis:
    container_name: schedule-redis
    image: redis
    networks:
      - schedule_network

  mongo:
    container_name: schedule-mongo
    image: mongo
    env_file: .env
    networks:
      - schedule_network
    volumes:
      - 'mongo_data:/data/db'

networks:
  schedule_network:
    name: schedule_network


volumes:
  postgres_data:
  mongo_data: 
