FROM node:18.16.0-alpine AS build-base

WORKDIR /app
COPY ./frontend /app
RUN npm config delete proxy
RUN npm install && npm run build

FROM nginx:latest
COPY --from=build-base /app/build /usr/share/nginx/html
COPY ./etc/nginx.scheduler-web.conf /etc/nginx/conf.d/default.conf
