---

- name: Configure databases
  hosts: instances_schedule_dbs
  vars_files: 
    - common.yaml
  remote_user: "{{ remote_user }}"
  become: true

  roles:
    - schedule_postgres
    - schedule_redis
    - schedule_mongo
