---

- name: Configure Redis
  hosts: instances_schedule_dbs
  remote_user: ec2-user
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - redis6

    - name: Install Python packages
      pip:
        name: "{{ item }}"
      with_items:
        - redis

    - name: Ensure that redis is started
      ansible.builtin.service:
        name: redis6
        state: started
        enabled: true

    - name: Run Redis on all interfaces
      lineinfile:
        path: /etc/redis6/redis6.conf
        regexp: '^bind'
        line: 'bind 0.0.0.0'
        state: present
      notify: restart redis


  handlers:
    - name: restart redis
      service:
        name: redis6
        state: restarted
