server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ loki_host }}:{{ loki_port }}/loki/api/v1/push

scrape_configs:
  - job_name: tomcat9
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      matches: _SYSTEMD_UNIT=tomcat9.service
      labels:
        job: tomcat9
        service: tomcat9
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
