---

- name: Install packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-11-amazon-corretto-headless
    - java-11-amazon-corretto-devel
    - tomcat9

- name: Ensure that tomcat9 is started
  ansible.builtin.service:
    name: tomcat9
    state: started
    enabled: true

- name: Copy WAR file
  ansible.builtin.copy:
    src: api-artifact
    dest: /usr/share/tomcat9/webapps/class_schedule.war
    mode: '0644'
  notify: restart tomcat9

- name: Ensure {{ scripts_home_dir }} dir exists
  ansible.builtin.file:
    path: "{{ scripts_home_dir }}"
    state: directory

- name: Copy script to update /etc/hosts file
  ansible.builtin.copy:
    src: update_hosts.sh
    dest: "{{ scripts_home_dir }}/update_hosts.sh"
    mode: '0744'

- name: Run update_hosts.sh script if /etc/hosts does not contain the necessary data
  ansible.builtin.shell: "/var/api_scripts/update_hosts.sh {{ update_hosts_arg }}"
  when: true
