#cloud-config

package_update: true

runcmd:
  - mkdir -p /var/sftp/data
  - chown root:root /var/sftp
  - chown sftpuser:sftp-users /var/sftp/data
  - chmod 755 /var/sftp
  - chmod 775 /var/sftp/data

groups:
  - admingroup: [root,sys]
  - cloud-users
  - sftp-users

users:
  - default
  - name: user # default sftp user
    groups:
      - cloud-users
      - sftp-users
    ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAf6V4g7ahli0x4Z8D3cbC3ZeT5li7p63zldIU0Wcijj
    lock_passwd: true
  - name: admin # use instead of ec2-user
    groups:
      - sudo
      - cloud-users
    sudo:
      - ALL=(ALL:ALL) NOPASSWD:ALL
    ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAf6V4g7ahli0x4Z8D3cbC3ZeT5li7p63zldIU0Wcijj
    lock_passwd: true
  - name: sftpuser # artifacts synchronization
    primary_group: sftpuser
    groups:
      - cloud-users
    homedir: /var/sftp
    ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAf6V4g7ahli0x4Z8D3cbC3ZeT5li7p63zldIU0Wcijj
    lock_passwd: true

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Match Group sftp-users
          ChrootDirectory /var/sftp
          X11Forwarding no
          AllowTcpForwarding no
          PasswordAuthentication no
          ForceCommand internal-sftp
    append: true


ssh_deletekeys: false
