#cloud-config

package_update: true

packages:
  - nginx

runcmd:
  - chown -R admin:admin /var/schedule_meta
  - /var/schedule_meta/download_web_tar.sh
  - systemctl enable nginx
  - systemctl start nginx

groups:
  - admingroup: [root,sys]
  - cloud-users

users:
  - default
  - name: admin
    groups:
      - sudo
      - cloud-users
    sudo:
      - ALL=(ALL:ALL) NOPASSWD:ALL
    ssh-authorized-keys:
     - ${web_public_key}
    lock_passwd: true

write_files:
  - path: /var/schedule_meta/sftp_ip
    content: |
      ${sftp_instance_ip}
  - path: /var/schedule_meta/sftp_key
    encoding: base64
    permissions: '0600'
    content: |
      ${sftp_user_private_key}
  - path: /var/schedule_meta/download_web_tar.sh
    encoding: base64
    permissions: '0700'
    content: |
      ${download_web_tar}

ssh_deletekeys: false
