---

- name: Install packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: Ensure that nginx is started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Copy contents of web-artifact to schedule_web directory
  ansible.builtin.copy:
    src: web-artifact/
    dest: /usr/share/nginx/schedule_web/
    mode: '0644'
    directory_mode: '0755'
    remote_src: no
  notify: restart nginx

- name: Copy nginx config for schedule_web application
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/conf.d/schedule_web.conf
    mode: '0644'
  notify: restart nginx

- name: Include exporter tasks
  ansible.builtin.include_tasks: ./prometheus_exporter.yml
