---

- name: Install packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - redis6

- name: Install Python packages
  pip:
    name: "{{ item }}"
  with_items:
    - redis

- name: Run Redis on all interfaces
  lineinfile:
    path: /etc/redis6/redis6.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'
    state: present
  notify: restart redis

- name: Disable Redis protected mode
  lineinfile:
    path: /etc/redis6/redis6.conf
    regexp: '^protected-mode'
    line: 'protected-mode no'

- name: Ensure that redis is started
  ansible.builtin.service:
    name: redis6
    state: started
    enabled: true
