kind: ConfigMap
apiVersion: v1
metadata:
  name: mongo
  namespace: default
data:
  MONGO_INITDB_DATABASE: schedules
  # TODO: move sensitive data to secrets
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin
