apiVersion: v1
kind: Service
metadata:
  name: schedule-mongo
  namespace: default
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
    - name: schedule-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
