apiVersion: v1
kind: Service
metadata:
  name: schedule-db
  namespace: default
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
    - name: schedule-db
      protocol: TCP
      port: 5432
      targetPort: 5432
