---
plugin: aws_ec2

regions:
  - eu-west-2

cache: true
cache_timeout: 3600

#aws_access_key: <YOUR-AWS-ACCESS-KEY-HERE>
#aws_secret_key: <YOUR-AWS-SECRET-KEY-HERE>

keyed_groups:
  - key: tags['Name']
    prefix: instances
