---

- name: Add mongo yum repository
  ansible.builtin.yum_repository:
    name: mongo
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
    gpgcheck: true
    enabled: true
    gpgkey: https://pgp.mongodb.com/server-7.0.asc

- name: Install MongoDB packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mongodb-mongosh-shared-openssl3
    - mongodb-org-database
    - mongodb-org-server

- name: Modify mongod.conf to bind MongoDB to all interfaces
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^  bindIp:'
    line: '  bindIp: 0.0.0.0'
    state: present
  notify: restart mongod

- name: Ensure that mongod is started
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true
