{
 "title": "Class Schedule",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Web",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nginx_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Panel Title",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 3, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nginx_connections_active", "legendFormat": "{{__name__}}" },
      { "expr": "nginx_connections_waiting", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "Endpoint usage",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 15, "x": 9, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_http_requests_total{instance=\"localhost:9090\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total http requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Requests statuses",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_total{instance=\"localhost:9090\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "PG exporter scrapes total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_exporter_scrapes_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "State of connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 18 },
     "targets": [
      { "expr": "pg_stat_activity_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Pg exporter errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_exporter_last_scrape_error", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Connections per database",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_stat_database_numbackends", "legendFormat": "{{datname}}" }
     ]
    },
    {
     "title": "Disk Read / Writes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 9, "y": 26 },
     "targets": [
      { "expr": "pg_stat_database_blk_read_time", "legendFormat": "__auto" },
      {
       "expr": "pg_stat_database_blk_write_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB sizes (in bytes)",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_database_size_bytes", "legendFormat": "{{datname}}" }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clients",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "clients", "type": "command" }
     ]
    },
    {
     "title": "Mode",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 13, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "server", "type": "command" }
     ]
    },
    {
     "title": "PID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "server", "type": "command" }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "server", "type": "command" }
     ]
    },
    {
     "title": "IO Threads active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "server", "type": "command" }
     ]
    },
    {
     "title": "Connection processed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "PubSub Channels",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "CPU consumption",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "cpu", "type": "command" }
     ]
    },
    {
     "title": "Errors",
     "type": "table",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 31 },
     "targets": [
      { "command": "info", "section": "errorstats", "type": "command" }
     ]
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Object size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_dbstats_avgObjSize", "legendFormat": "{{database}}" }
     ]
    },
    {
     "title": "Op counter",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 10, "x": 7, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_ss_opcounters", "legendFormat": "{{legacy_op_type}}" }
     ]
    },
    {
     "title": "Virtual mem",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
     "targets": [
      { "expr": "mongodb_ss_mem_virtual", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Connections",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_ss_connections", "legendFormat": "{{conn_type}}" }
     ]
    },
    {
     "title": "Indexes",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 9, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_dbstats_indexes", "legendFormat": "{{database}}" }
     ]
    },
    {
     "title": "Data size",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 13, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_dbstats_dataSize", "legendFormat": "{{database}}" }
     ]
    },
    {
     "title": "Fs used size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 28 },
     "targets": [
      { "expr": "mongodb_dbstats_fsUsedSize", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "AWS instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Uptime (hours)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds) / 3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[10m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[10m])) / avg_over_time(node_memory_MemTotal_bytes[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (user)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmit (in Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(node_network_transmit_bytes_total) by (instance) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root FS usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /  node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}